# -*- mode: python -*-

block_cipher = None

a = Analysis(['..\\..\\Perun.py'],
             binaries=[],
             datas=[],
             hiddenimports=[ 'io',
                             'os',
                             're',
                             'sys',
                             'ssl',
                             'time',
                             'json',
                             'Queue',
                             'base64',
                             'ftplib',
                             'random',
                             'urllib',
                             'socket',
                             'string',
                             'struct',
                             'difflib',
                             'hashlib',
                             'urllib2',
                             'argparse',
                             'binascii',
                             'urlparse',
                             'itertools',
                             'threading',
                             'subprocess',
                           ],
             hookspath=[],
             runtime_hooks=[],
             excludes=[],
             win_no_prefer_redirects=False,
             win_private_assemblies=False,
             cipher=block_cipher,
             noarchive=False)
pyz = PYZ(a.pure, a.zipped_data,
             cipher=block_cipher)
exe = EXE(pyz,
          a.scripts,
          a.binaries,
          a.zipfiles,
          a.datas,
          [],
          name='Perun',
          debug=False,
          bootloader_ignore_signals=False,
          strip=False,
          upx=True,
          runtime_tmpdir=None,
          console=True )
